### ISSUE TITLE
TypeError: decoding Unicode is not supported

### ISSUE THREAD

**Issue by andybak** [jsoa/django-formfield#12]
Using the js/0.3 branch.

In 393b8a104caab26af18a6e0c34773d6a537623f6 you changed formfield/widgets.py L52:

    return ''.join(ret)

to:

    return six.u(''.join(ret))

In Python2.7 and Django1.8 I've getting TypeError: decoding Unicode is not supported when rendering the admin changeform. Changing that back fixes it.

**Comment by jsoa** [comment]
@andybak updated in bb5fe741e4fe74aa6634afe833d82129c43d4dc8 (in the `js/0.3` branch)
