### ISSUE TITLE
Signature for ModelFormField has changed

### ISSUE THREAD

**Issue by andybak** [jsoa/django-formfield#13]
In js/0.3 latest head - contrary to docs I need to do:

    foo = ModelFormField(form=FooForm)

(note the keyword arg)

I guess this is just the docs lagging behind code changes?

**Comment by jsoa** [comment]
Thats correct, `0.3` makes it required to use the kwarg `form`. I updated some of the docs in the `0.3` branch to reflect this change. Ill take another look to see if I missed some other references.
