### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by Benoss** [jsoa/django-formfield#18]
I've seen a pull request for django 1.9
https://github.com/jsoa/django-formfield/pull/17
Do you plan to work a bit on this project for the new LTS? Just to know if I should fork it. Unless you know any other alternatives

**Comment by jsoa** [comment]
Updated 0.4 branch to include django 1.8+ compat (including 1.11rc1)

**Comment by Benoss** [comment]
Thank, looks good !
